# Generated by Django 6.0 on 2026-01-08 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('atual', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('cursando', 'Cursando'), ('trancado', 'Trancado')], max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente')], max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_profissional', models.CharField(help_text='Ex: João Silva | Desenvolvedor Full Stack', max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('resumo_profissional', models.TextField()),
                ('pretensao_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponibilidade', models.CharField(choices=[('imediata', 'Imediata'), ('15_dias', '15 dias'), ('30_dias', '30 dias')], max_length=20)),
                ('modelo_trabalho', models.CharField(choices=[('remoto', 'Remoto'), ('hibrido', 'Híbrido'), ('presencial', 'Presencial')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_vaga', models.CharField(max_length=50, unique=True)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('modelo_trabalho', models.CharField(choices=[('remoto', 'Remoto'), ('hibrido', 'Híbrido'), ('presencial', 'Presencial')], max_length=20)),
                ('localizacao', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('temporario', 'Temporário')], max_length=20)),
                ('carga_horaria', models.CharField(max_length=50)),
                ('resumo', models.TextField()),
                ('responsabilidades', models.TextField()),
                ('requisitos_obrigatorios', models.TextField()),
                ('requisitos_desejaveis', models.TextField(blank=True)),
                ('soft_skills', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etapas_processo', models.TextField(blank=True)),
                ('cultura_empresa', models.URLField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='enviada', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='core.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'candidato')},
            },
        ),
    ]
