# Generated by Django 6.0 on 2026-01-11 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('atual', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(choices=[('ensino_medio', 'Ensino Médio'), ('tecnico', 'Curso Técnico'), ('tecnologo', 'Graduação Tecnológica (Tecnólogo)'), ('bacharelado', 'Bacharelado'), ('licenciatura', 'Licenciatura'), ('pos_graduacao', 'Pós-Graduação (Lato Sensu)'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('mba', 'MBA')], max_length=50)),
                ('curso', models.CharField(max_length=150)),
                ('instituicao', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('cursando', 'Cursando'), ('interrompido', 'Interrompido')], max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente')], max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('titulo_profissional', models.CharField(help_text='Ex: Desenvolvedor Full Stack PHP / React', max_length=150, verbose_name='Título Profissional')),
                ('resumo_profissional', models.TextField(help_text='Fale um pouco sobre sua trajetória e principais competências.', verbose_name='Resumo Profissional')),
                ('email_contato', models.EmailField(blank=True, help_text='Email que os recrutadores usarão para falar com você.', max_length=255, null=True, verbose_name='E-mail de Contato')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp/Telefone')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('portfolio', models.URLField(blank=True, verbose_name='Portfólio/Site')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Sigla (Ex: SP, RJ)', max_length=2, verbose_name='Estado (UF)')),
                ('modelo_trabalho', models.CharField(choices=[('remoto', 'Remoto'), ('hibrido', 'Híbrido'), ('presencial', 'Presencial')], max_length=20, verbose_name='Modelo de Trabalho Preferido')),
                ('disponibilidade', models.CharField(choices=[('imediata', 'Imediata'), ('15_dias', '15 dias'), ('30_dias', '30 dias')], max_length=20, verbose_name='Disponibilidade para Início')),
                ('pretensao_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pretensão Salarial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa')], max_length=20)),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome ou Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_vaga', models.CharField(max_length=50, unique=True)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('modelo_trabalho', models.CharField(choices=[('remoto', 'Remoto'), ('hibrido', 'Híbrido'), ('presencial', 'Presencial')], max_length=20)),
                ('localizacao', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('temporario', 'Temporário')], max_length=20)),
                ('carga_horaria', models.CharField(max_length=50)),
                ('resumo', models.TextField()),
                ('responsabilidades', models.TextField()),
                ('requisitos_obrigatorios', models.TextField()),
                ('requisitos_desejaveis', models.TextField(blank=True)),
                ('soft_skills', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etapas_processo', models.TextField(blank=True)),
                ('cultura_empresa', models.URLField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='enviada', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='core.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'candidato')},
            },
        ),
    ]
