# Generated by Django 6.0 on 2026-01-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
