# Generated by Django 6.0 on 2026-01-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disponivel_para_alocacao',
            field=models.BooleanField(default=False, verbose_name='Banco de Talentos TrabalheJá'),
        ),
    ]
